# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import faultline_pb2 as faultline__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in faultline_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FaultlineServiceStub(object):
    """Faultline checkpoint gRPC API (optional transport alongside JSON stdin/stdout services).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveFromFile = channel.unary_unary(
                '/faultline.FaultlineService/SaveFromFile',
                request_serializer=faultline__pb2.SaveFromFileRequest.SerializeToString,
                response_deserializer=faultline__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.EnqueueWorkerFromFile = channel.unary_unary(
                '/faultline.FaultlineService/EnqueueWorkerFromFile',
                request_serializer=faultline__pb2.EnqueueWorkerFromFileRequest.SerializeToString,
                response_deserializer=faultline__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.EnqueueWorkerBytes = channel.unary_unary(
                '/faultline.FaultlineService/EnqueueWorkerBytes',
                request_serializer=faultline__pb2.EnqueueWorkerBytesRequest.SerializeToString,
                response_deserializer=faultline__pb2.EnqueueResponse.FromString,
                _registered_method=True)
        self.EnqueueWorkerBytesStream = channel.stream_unary(
                '/faultline.FaultlineService/EnqueueWorkerBytesStream',
                request_serializer=faultline__pb2.CheckpointChunk.SerializeToString,
                response_deserializer=faultline__pb2.EnqueueResponse.FromString,
                _registered_method=True)
        self.LatestForWorker = channel.unary_unary(
                '/faultline.FaultlineService/LatestForWorker',
                request_serializer=faultline__pb2.LatestForWorkerRequest.SerializeToString,
                response_deserializer=faultline__pb2.LatestForWorkerResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/faultline.FaultlineService/Status',
                request_serializer=faultline__pb2.StatusRequest.SerializeToString,
                response_deserializer=faultline__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Metrics = channel.unary_unary(
                '/faultline.FaultlineService/Metrics',
                request_serializer=faultline__pb2.MetricsRequest.SerializeToString,
                response_deserializer=faultline__pb2.MetricsResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/faultline.FaultlineService/Shutdown',
                request_serializer=faultline__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=faultline__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.RegisterDataset = channel.unary_unary(
                '/faultline.FaultlineService/RegisterDataset',
                request_serializer=faultline__pb2.RegisterDatasetRequest.SerializeToString,
                response_deserializer=faultline__pb2.RegisterDatasetResponse.FromString,
                _registered_method=True)
        self.ListDatasets = channel.unary_unary(
                '/faultline.FaultlineService/ListDatasets',
                request_serializer=faultline__pb2.ListDatasetsRequest.SerializeToString,
                response_deserializer=faultline__pb2.ListDatasetsResponse.FromString,
                _registered_method=True)
        self.ClaimNextShard = channel.unary_unary(
                '/faultline.FaultlineService/ClaimNextShard',
                request_serializer=faultline__pb2.ClaimNextShardRequest.SerializeToString,
                response_deserializer=faultline__pb2.ClaimNextShardResponse.FromString,
                _registered_method=True)
        self.CompleteShard = channel.unary_unary(
                '/faultline.FaultlineService/CompleteShard',
                request_serializer=faultline__pb2.CompleteShardRequest.SerializeToString,
                response_deserializer=faultline__pb2.CompleteShardResponse.FromString,
                _registered_method=True)
        self.ReleaseStaleShards = channel.unary_unary(
                '/faultline.FaultlineService/ReleaseStaleShards',
                request_serializer=faultline__pb2.ReleaseStaleShardsRequest.SerializeToString,
                response_deserializer=faultline__pb2.ReleaseStaleShardsResponse.FromString,
                _registered_method=True)
        self.GetRuntimeOverview = channel.unary_unary(
                '/faultline.FaultlineService/GetRuntimeOverview',
                request_serializer=faultline__pb2.GetRuntimeOverviewRequest.SerializeToString,
                response_deserializer=faultline__pb2.GetRuntimeOverviewResponse.FromString,
                _registered_method=True)
        self.ListWorkers = channel.unary_unary(
                '/faultline.FaultlineService/ListWorkers',
                request_serializer=faultline__pb2.ListWorkersRequest.SerializeToString,
                response_deserializer=faultline__pb2.ListWorkersResponse.FromString,
                _registered_method=True)
        self.ListShards = channel.unary_unary(
                '/faultline.FaultlineService/ListShards',
                request_serializer=faultline__pb2.ListShardsRequest.SerializeToString,
                response_deserializer=faultline__pb2.ListShardsResponse.FromString,
                _registered_method=True)
        self.ListEvents = channel.unary_unary(
                '/faultline.FaultlineService/ListEvents',
                request_serializer=faultline__pb2.ListEventsRequest.SerializeToString,
                response_deserializer=faultline__pb2.ListEventsResponse.FromString,
                _registered_method=True)
        self.CreateRun = channel.unary_unary(
                '/faultline.FaultlineService/CreateRun',
                request_serializer=faultline__pb2.CreateRunRequest.SerializeToString,
                response_deserializer=faultline__pb2.CreateRunResponse.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/faultline.FaultlineService/ListRuns',
                request_serializer=faultline__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=faultline__pb2.ListRunsResponse.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/faultline.FaultlineService/GetRun',
                request_serializer=faultline__pb2.GetRunRequest.SerializeToString,
                response_deserializer=faultline__pb2.GetRunResponse.FromString,
                _registered_method=True)
        self.UpdateRunMetrics = channel.unary_unary(
                '/faultline.FaultlineService/UpdateRunMetrics',
                request_serializer=faultline__pb2.UpdateRunMetricsRequest.SerializeToString,
                response_deserializer=faultline__pb2.UpdateRunMetricsResponse.FromString,
                _registered_method=True)
        self.LogRunMetrics = channel.unary_unary(
                '/faultline.FaultlineService/LogRunMetrics',
                request_serializer=faultline__pb2.LogRunMetricsRequest.SerializeToString,
                response_deserializer=faultline__pb2.LogRunMetricsResponse.FromString,
                _registered_method=True)
        self.ListRunMetrics = channel.unary_unary(
                '/faultline.FaultlineService/ListRunMetrics',
                request_serializer=faultline__pb2.ListRunMetricsRequest.SerializeToString,
                response_deserializer=faultline__pb2.ListRunMetricsResponse.FromString,
                _registered_method=True)
        self.CompleteRun = channel.unary_unary(
                '/faultline.FaultlineService/CompleteRun',
                request_serializer=faultline__pb2.CompleteRunRequest.SerializeToString,
                response_deserializer=faultline__pb2.CompleteRunResponse.FromString,
                _registered_method=True)
        self.ListAlerts = channel.unary_unary(
                '/faultline.FaultlineService/ListAlerts',
                request_serializer=faultline__pb2.ListAlertsRequest.SerializeToString,
                response_deserializer=faultline__pb2.ListAlertsResponse.FromString,
                _registered_method=True)
        self.EvaluateAlerts = channel.unary_unary(
                '/faultline.FaultlineService/EvaluateAlerts',
                request_serializer=faultline__pb2.EvaluateAlertsRequest.SerializeToString,
                response_deserializer=faultline__pb2.EvaluateAlertsResponse.FromString,
                _registered_method=True)


class FaultlineServiceServicer(object):
    """Faultline checkpoint gRPC API (optional transport alongside JSON stdin/stdout services).
    """

    def SaveFromFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueueWorkerFromFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueueWorkerBytes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueueWorkerBytesStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LatestForWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Metrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatasets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimNextShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseStaleShards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeOverview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListShards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRunMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogRunMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAlerts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateAlerts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaultlineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveFromFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveFromFile,
                    request_deserializer=faultline__pb2.SaveFromFileRequest.FromString,
                    response_serializer=faultline__pb2.GenericResponse.SerializeToString,
            ),
            'EnqueueWorkerFromFile': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueWorkerFromFile,
                    request_deserializer=faultline__pb2.EnqueueWorkerFromFileRequest.FromString,
                    response_serializer=faultline__pb2.GenericResponse.SerializeToString,
            ),
            'EnqueueWorkerBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueWorkerBytes,
                    request_deserializer=faultline__pb2.EnqueueWorkerBytesRequest.FromString,
                    response_serializer=faultline__pb2.EnqueueResponse.SerializeToString,
            ),
            'EnqueueWorkerBytesStream': grpc.stream_unary_rpc_method_handler(
                    servicer.EnqueueWorkerBytesStream,
                    request_deserializer=faultline__pb2.CheckpointChunk.FromString,
                    response_serializer=faultline__pb2.EnqueueResponse.SerializeToString,
            ),
            'LatestForWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.LatestForWorker,
                    request_deserializer=faultline__pb2.LatestForWorkerRequest.FromString,
                    response_serializer=faultline__pb2.LatestForWorkerResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=faultline__pb2.StatusRequest.FromString,
                    response_serializer=faultline__pb2.StatusResponse.SerializeToString,
            ),
            'Metrics': grpc.unary_unary_rpc_method_handler(
                    servicer.Metrics,
                    request_deserializer=faultline__pb2.MetricsRequest.FromString,
                    response_serializer=faultline__pb2.MetricsResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=faultline__pb2.ShutdownRequest.FromString,
                    response_serializer=faultline__pb2.GenericResponse.SerializeToString,
            ),
            'RegisterDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDataset,
                    request_deserializer=faultline__pb2.RegisterDatasetRequest.FromString,
                    response_serializer=faultline__pb2.RegisterDatasetResponse.SerializeToString,
            ),
            'ListDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatasets,
                    request_deserializer=faultline__pb2.ListDatasetsRequest.FromString,
                    response_serializer=faultline__pb2.ListDatasetsResponse.SerializeToString,
            ),
            'ClaimNextShard': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimNextShard,
                    request_deserializer=faultline__pb2.ClaimNextShardRequest.FromString,
                    response_serializer=faultline__pb2.ClaimNextShardResponse.SerializeToString,
            ),
            'CompleteShard': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteShard,
                    request_deserializer=faultline__pb2.CompleteShardRequest.FromString,
                    response_serializer=faultline__pb2.CompleteShardResponse.SerializeToString,
            ),
            'ReleaseStaleShards': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseStaleShards,
                    request_deserializer=faultline__pb2.ReleaseStaleShardsRequest.FromString,
                    response_serializer=faultline__pb2.ReleaseStaleShardsResponse.SerializeToString,
            ),
            'GetRuntimeOverview': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeOverview,
                    request_deserializer=faultline__pb2.GetRuntimeOverviewRequest.FromString,
                    response_serializer=faultline__pb2.GetRuntimeOverviewResponse.SerializeToString,
            ),
            'ListWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkers,
                    request_deserializer=faultline__pb2.ListWorkersRequest.FromString,
                    response_serializer=faultline__pb2.ListWorkersResponse.SerializeToString,
            ),
            'ListShards': grpc.unary_unary_rpc_method_handler(
                    servicer.ListShards,
                    request_deserializer=faultline__pb2.ListShardsRequest.FromString,
                    response_serializer=faultline__pb2.ListShardsResponse.SerializeToString,
            ),
            'ListEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvents,
                    request_deserializer=faultline__pb2.ListEventsRequest.FromString,
                    response_serializer=faultline__pb2.ListEventsResponse.SerializeToString,
            ),
            'CreateRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRun,
                    request_deserializer=faultline__pb2.CreateRunRequest.FromString,
                    response_serializer=faultline__pb2.CreateRunResponse.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=faultline__pb2.ListRunsRequest.FromString,
                    response_serializer=faultline__pb2.ListRunsResponse.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=faultline__pb2.GetRunRequest.FromString,
                    response_serializer=faultline__pb2.GetRunResponse.SerializeToString,
            ),
            'UpdateRunMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRunMetrics,
                    request_deserializer=faultline__pb2.UpdateRunMetricsRequest.FromString,
                    response_serializer=faultline__pb2.UpdateRunMetricsResponse.SerializeToString,
            ),
            'LogRunMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.LogRunMetrics,
                    request_deserializer=faultline__pb2.LogRunMetricsRequest.FromString,
                    response_serializer=faultline__pb2.LogRunMetricsResponse.SerializeToString,
            ),
            'ListRunMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunMetrics,
                    request_deserializer=faultline__pb2.ListRunMetricsRequest.FromString,
                    response_serializer=faultline__pb2.ListRunMetricsResponse.SerializeToString,
            ),
            'CompleteRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteRun,
                    request_deserializer=faultline__pb2.CompleteRunRequest.FromString,
                    response_serializer=faultline__pb2.CompleteRunResponse.SerializeToString,
            ),
            'ListAlerts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAlerts,
                    request_deserializer=faultline__pb2.ListAlertsRequest.FromString,
                    response_serializer=faultline__pb2.ListAlertsResponse.SerializeToString,
            ),
            'EvaluateAlerts': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateAlerts,
                    request_deserializer=faultline__pb2.EvaluateAlertsRequest.FromString,
                    response_serializer=faultline__pb2.EvaluateAlertsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'faultline.FaultlineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('faultline.FaultlineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FaultlineService(object):
    """Faultline checkpoint gRPC API (optional transport alongside JSON stdin/stdout services).
    """

    @staticmethod
    def SaveFromFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/SaveFromFile',
            faultline__pb2.SaveFromFileRequest.SerializeToString,
            faultline__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueueWorkerFromFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/EnqueueWorkerFromFile',
            faultline__pb2.EnqueueWorkerFromFileRequest.SerializeToString,
            faultline__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueueWorkerBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/EnqueueWorkerBytes',
            faultline__pb2.EnqueueWorkerBytesRequest.SerializeToString,
            faultline__pb2.EnqueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueueWorkerBytesStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/faultline.FaultlineService/EnqueueWorkerBytesStream',
            faultline__pb2.CheckpointChunk.SerializeToString,
            faultline__pb2.EnqueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LatestForWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/LatestForWorker',
            faultline__pb2.LatestForWorkerRequest.SerializeToString,
            faultline__pb2.LatestForWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/Status',
            faultline__pb2.StatusRequest.SerializeToString,
            faultline__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Metrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/Metrics',
            faultline__pb2.MetricsRequest.SerializeToString,
            faultline__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/Shutdown',
            faultline__pb2.ShutdownRequest.SerializeToString,
            faultline__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/RegisterDataset',
            faultline__pb2.RegisterDatasetRequest.SerializeToString,
            faultline__pb2.RegisterDatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/ListDatasets',
            faultline__pb2.ListDatasetsRequest.SerializeToString,
            faultline__pb2.ListDatasetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimNextShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/ClaimNextShard',
            faultline__pb2.ClaimNextShardRequest.SerializeToString,
            faultline__pb2.ClaimNextShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/CompleteShard',
            faultline__pb2.CompleteShardRequest.SerializeToString,
            faultline__pb2.CompleteShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseStaleShards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/ReleaseStaleShards',
            faultline__pb2.ReleaseStaleShardsRequest.SerializeToString,
            faultline__pb2.ReleaseStaleShardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeOverview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/GetRuntimeOverview',
            faultline__pb2.GetRuntimeOverviewRequest.SerializeToString,
            faultline__pb2.GetRuntimeOverviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/ListWorkers',
            faultline__pb2.ListWorkersRequest.SerializeToString,
            faultline__pb2.ListWorkersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListShards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/ListShards',
            faultline__pb2.ListShardsRequest.SerializeToString,
            faultline__pb2.ListShardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/ListEvents',
            faultline__pb2.ListEventsRequest.SerializeToString,
            faultline__pb2.ListEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/CreateRun',
            faultline__pb2.CreateRunRequest.SerializeToString,
            faultline__pb2.CreateRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/ListRuns',
            faultline__pb2.ListRunsRequest.SerializeToString,
            faultline__pb2.ListRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/GetRun',
            faultline__pb2.GetRunRequest.SerializeToString,
            faultline__pb2.GetRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRunMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/UpdateRunMetrics',
            faultline__pb2.UpdateRunMetricsRequest.SerializeToString,
            faultline__pb2.UpdateRunMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogRunMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/LogRunMetrics',
            faultline__pb2.LogRunMetricsRequest.SerializeToString,
            faultline__pb2.LogRunMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRunMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/ListRunMetrics',
            faultline__pb2.ListRunMetricsRequest.SerializeToString,
            faultline__pb2.ListRunMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/CompleteRun',
            faultline__pb2.CompleteRunRequest.SerializeToString,
            faultline__pb2.CompleteRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/ListAlerts',
            faultline__pb2.ListAlertsRequest.SerializeToString,
            faultline__pb2.ListAlertsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/EvaluateAlerts',
            faultline__pb2.EvaluateAlertsRequest.SerializeToString,
            faultline__pb2.EvaluateAlertsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
