# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import faultline_pb2 as faultline__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in faultline_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FaultlineServiceStub(object):
    """Faultline checkpoint gRPC API (optional transport alongside JSON stdin/stdout services).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveFromFile = channel.unary_unary(
                '/faultline.FaultlineService/SaveFromFile',
                request_serializer=faultline__pb2.SaveFromFileRequest.SerializeToString,
                response_deserializer=faultline__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.EnqueueWorkerFromFile = channel.unary_unary(
                '/faultline.FaultlineService/EnqueueWorkerFromFile',
                request_serializer=faultline__pb2.EnqueueWorkerFromFileRequest.SerializeToString,
                response_deserializer=faultline__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.EnqueueWorkerBytes = channel.unary_unary(
                '/faultline.FaultlineService/EnqueueWorkerBytes',
                request_serializer=faultline__pb2.EnqueueWorkerBytesRequest.SerializeToString,
                response_deserializer=faultline__pb2.EnqueueResponse.FromString,
                _registered_method=True)
        self.EnqueueWorkerBytesStream = channel.stream_unary(
                '/faultline.FaultlineService/EnqueueWorkerBytesStream',
                request_serializer=faultline__pb2.CheckpointChunk.SerializeToString,
                response_deserializer=faultline__pb2.EnqueueResponse.FromString,
                _registered_method=True)
        self.LatestForWorker = channel.unary_unary(
                '/faultline.FaultlineService/LatestForWorker',
                request_serializer=faultline__pb2.LatestForWorkerRequest.SerializeToString,
                response_deserializer=faultline__pb2.LatestForWorkerResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/faultline.FaultlineService/Status',
                request_serializer=faultline__pb2.StatusRequest.SerializeToString,
                response_deserializer=faultline__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Metrics = channel.unary_unary(
                '/faultline.FaultlineService/Metrics',
                request_serializer=faultline__pb2.MetricsRequest.SerializeToString,
                response_deserializer=faultline__pb2.MetricsResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/faultline.FaultlineService/Shutdown',
                request_serializer=faultline__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=faultline__pb2.GenericResponse.FromString,
                _registered_method=True)


class FaultlineServiceServicer(object):
    """Faultline checkpoint gRPC API (optional transport alongside JSON stdin/stdout services).
    """

    def SaveFromFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueueWorkerFromFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueueWorkerBytes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueueWorkerBytesStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LatestForWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Metrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaultlineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveFromFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveFromFile,
                    request_deserializer=faultline__pb2.SaveFromFileRequest.FromString,
                    response_serializer=faultline__pb2.GenericResponse.SerializeToString,
            ),
            'EnqueueWorkerFromFile': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueWorkerFromFile,
                    request_deserializer=faultline__pb2.EnqueueWorkerFromFileRequest.FromString,
                    response_serializer=faultline__pb2.GenericResponse.SerializeToString,
            ),
            'EnqueueWorkerBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueWorkerBytes,
                    request_deserializer=faultline__pb2.EnqueueWorkerBytesRequest.FromString,
                    response_serializer=faultline__pb2.EnqueueResponse.SerializeToString,
            ),
            'EnqueueWorkerBytesStream': grpc.stream_unary_rpc_method_handler(
                    servicer.EnqueueWorkerBytesStream,
                    request_deserializer=faultline__pb2.CheckpointChunk.FromString,
                    response_serializer=faultline__pb2.EnqueueResponse.SerializeToString,
            ),
            'LatestForWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.LatestForWorker,
                    request_deserializer=faultline__pb2.LatestForWorkerRequest.FromString,
                    response_serializer=faultline__pb2.LatestForWorkerResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=faultline__pb2.StatusRequest.FromString,
                    response_serializer=faultline__pb2.StatusResponse.SerializeToString,
            ),
            'Metrics': grpc.unary_unary_rpc_method_handler(
                    servicer.Metrics,
                    request_deserializer=faultline__pb2.MetricsRequest.FromString,
                    response_serializer=faultline__pb2.MetricsResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=faultline__pb2.ShutdownRequest.FromString,
                    response_serializer=faultline__pb2.GenericResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'faultline.FaultlineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('faultline.FaultlineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FaultlineService(object):
    """Faultline checkpoint gRPC API (optional transport alongside JSON stdin/stdout services).
    """

    @staticmethod
    def SaveFromFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/SaveFromFile',
            faultline__pb2.SaveFromFileRequest.SerializeToString,
            faultline__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueueWorkerFromFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/EnqueueWorkerFromFile',
            faultline__pb2.EnqueueWorkerFromFileRequest.SerializeToString,
            faultline__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueueWorkerBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/EnqueueWorkerBytes',
            faultline__pb2.EnqueueWorkerBytesRequest.SerializeToString,
            faultline__pb2.EnqueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueueWorkerBytesStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/faultline.FaultlineService/EnqueueWorkerBytesStream',
            faultline__pb2.CheckpointChunk.SerializeToString,
            faultline__pb2.EnqueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LatestForWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/LatestForWorker',
            faultline__pb2.LatestForWorkerRequest.SerializeToString,
            faultline__pb2.LatestForWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/Status',
            faultline__pb2.StatusRequest.SerializeToString,
            faultline__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Metrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/Metrics',
            faultline__pb2.MetricsRequest.SerializeToString,
            faultline__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineService/Shutdown',
            faultline__pb2.ShutdownRequest.SerializeToString,
            faultline__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
